export const TARGET_CHAIN_ID = 421614;

export type OptionalWeb3FlowAdapter<T> = {
  precheck?: (input: T) => Promise<T> | T;
  decodeError?: (error: unknown, fallbackMessage: string) => string;
};

export async function runOptionalWeb3Precheck<T>(
  adapter: OptionalWeb3FlowAdapter<T> | undefined,
  input: T,
): Promise<T> {
  if (!adapter?.precheck) {
    return input;
  }
  return adapter.precheck(input);
}

export function decodeWeb3FlowError<T>(
  error: unknown,
  fallbackMessage: string,
  adapter?: OptionalWeb3FlowAdapter<T>,
): string {
  if (adapter?.decodeError) {
    return adapter.decodeError(error, fallbackMessage);
  }

  const message = error instanceof Error ? error.message : String(error ?? "");
  const normalized = message.trim();
  const lower = normalized.toLowerCase();

  if (!normalized) {
    return fallbackMessage;
  }
  if (lower.includes("user rejected") || lower.includes("user denied") || lower.includes("rejected the request")) {
    return "Wallet request was rejected. Re-open the wallet prompt and approve the transaction to continue.";
  }
  if (lower.includes("switchchain") || lower.includes("wrong network") || lower.includes("chain mismatch")) {
    return `Wallet is on the wrong network. Switch to Arbitrum Sepolia (chain ID ${TARGET_CHAIN_ID}) and retry.`;
  }
  if (lower.includes("insufficient funds")) {
    return "Connected wallet does not have enough gas to submit this transaction.";
  }
  if (lower.includes("wallet session")) {
    return "Wallet session expired. Reconnect the wallet, then retry the submission.";
  }
  if (lower.includes("failed to reach backend") || lower.includes("fetch failed") || lower.includes("networkerror")) {
    return "Frontend could not reach the backend service. Confirm the API is up, then retry.";
  }
  if (lower.includes("insufficient role") || lower.includes("forbidden")) {
    return "Current signed-in role is not allowed to perform this action.";
  }
  if (lower.includes("unknown field") || lower.includes("schema")) {
    return "Frontend and backend payloads are out of sync. Refresh the app and confirm the related backend workstream is deployed.";
  }
  if (lower.includes("invalid json")) {
    return "The request payload generated by this page was invalid. Refresh the page and retry.";
  }

  return normalized;
}

export function isBytes32Hex(value: string): boolean {
  return /^0x[a-fA-F0-9]{64}$/.test(value.trim());
}

export function isTxHash(value: string): boolean {
  return /^0x[a-fA-F0-9]{64}$/.test(value.trim());
}

export function parsePositiveInteger(value: string | number): number | null {
  const parsed = typeof value === "number" ? value : Number(String(value).trim());
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

export function formatUnixTimestamp(timestamp: number): string {
  return new Date(timestamp * 1000).toISOString().replace("T", " ").replace(".000Z", " UTC");
}
